"""
Turn model/scorecard.json into a Supabase migration.

The scorecard lives in a table (public.scorecard_bins) so a retrained model is just
new rows plus one switch in app_settings ('credit_model_version'), not new code.
compute_credit_score() reads the active version, computes the same features the
model was trained on, adds up points, and stores per-feature points so the app can
show reason codes ("what's lowering your score").

Usage: python export_sql.py > ../../supabase/migrations/<timestamp>_credit_scorecard_v1.sql
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
model = json.loads((HERE / "model" / "scorecard.json").read_text())
v = model["model_version"]


def lit(x):
    return "NULL" if x is None else repr(float(x))


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


rows = []
for f in model["features"]:
    for i, b in enumerate(f["bins"]):
        rows.append(
            f"  ({q(v)}, {q(f['feature'])}, {q(f['label'])}, {i}, {lit(b['min'])}, {lit(b['max'])}, "
            f"{b['points']}, {b['woe']}, {b['default_rate']})"
        )

bands = model["bands"]
band_case = "\n".join(f"    WHEN v_score >= {b['min']} THEN '{b['band']}'" for b in bands[:-1])

print(f"""-- ============================================================================
-- Credit scorecard {v} (generated by ml/credit-model/export_sql.py — do not hand-edit)
-- Logistic-regression scorecard on WoE-binned behaviour features.
-- Trained on SYNTHETIC data: retrain on real repayment outcomes before real lending.
-- Holdout metrics and method: ml/credit-model/MODEL_CARD.md
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.scorecard_bins (
  model_version text NOT NULL,
  feature text NOT NULL,
  label text NOT NULL,
  bin_no int NOT NULL,
  min_value numeric,          -- inclusive; NULL = no lower bound
  max_value numeric,          -- exclusive; NULL = no upper bound
  points int NOT NULL,
  woe numeric NOT NULL,
  train_default_rate numeric NOT NULL,
  PRIMARY KEY (model_version, feature, bin_no)
);
ALTER TABLE public.scorecard_bins ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.scorecard_bins TO authenticated;
GRANT ALL ON public.scorecard_bins TO service_role;
DO $p$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'scorecard_bins'
                 AND policyname = 'Signed-in users can read the scorecard') THEN
    CREATE POLICY "Signed-in users can read the scorecard" ON public.scorecard_bins
      FOR SELECT TO authenticated USING (true);
  END IF;
END $p$;

INSERT INTO public.scorecard_bins
  (model_version, feature, label, bin_no, min_value, max_value, points, woe, train_default_rate)
VALUES
{",\n".join(rows)}
ON CONFLICT (model_version, feature, bin_no) DO UPDATE
  SET label = EXCLUDED.label, min_value = EXCLUDED.min_value, max_value = EXCLUDED.max_value,
      points = EXCLUDED.points, woe = EXCLUDED.woe, train_default_rate = EXCLUDED.train_default_rate;

INSERT INTO public.app_settings (key, value) VALUES ('credit_model_version', {q(v)})
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

CREATE OR REPLACE FUNCTION public.compute_credit_score(_user_id uuid)
RETURNS int LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_model text;
  f jsonb;              -- feature values
  pts jsonb := '{{}}'::jsonb;
  max_pts jsonb := '{{}}'::jsonb;
  r record;
  v_income bigint; v_expense bigint;
  v_score int := 0; v_band text;
BEGIN
  IF auth.uid() IS NOT NULL AND auth.uid() <> _user_id AND NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  SELECT value INTO v_model FROM public.app_settings WHERE key = 'credit_model_version';
  v_model := COALESCE(v_model, {q(v)});

  SELECT COALESCE(SUM(amount), 0) INTO v_income FROM public.income_logs
   WHERE user_id = _user_id AND date > now() - interval '30 days';
  SELECT COALESCE(SUM(amount), 0) INTO v_expense FROM public.expenses
   WHERE user_id = _user_id AND date > now() - interval '30 days';

  -- Features: names and definitions must match ml/credit-model/generate_data.py
  f := jsonb_build_object(
    'income_days_30', (SELECT COUNT(DISTINCT (date AT TIME ZONE 'Asia/Kolkata')::date) FROM public.income_logs
                        WHERE user_id = _user_id AND date > now() - interval '30 days'),
    'income_total_30', v_income,
    'active_weeks_12', (SELECT COUNT(DISTINCT date_trunc('week', date AT TIME ZONE 'Asia/Kolkata')) FROM public.income_logs
                        WHERE user_id = _user_id AND date > now() - interval '84 days'),
    'expense_ratio_30', CASE WHEN v_income > 0 THEN LEAST(round(v_expense::numeric / v_income, 3), 2.0) ELSE 2.0 END,
    'savings_balance', (SELECT COALESCE(SUM(current_amount), 0) FROM public.savings_goals WHERE user_id = _user_id),
    -- only loans that actually paid out count (no fake history)
    'loans_repaid_on_time', (SELECT COUNT(*) FROM public.loans l
        WHERE l.user_id = _user_id AND l.status IN ('repaid','closed')
          AND EXISTS (SELECT 1 FROM public.loan_ledger d WHERE d.loan_id = l.id AND d.entry_type = 'disbursal')
          AND (l.due_date IS NULL OR (SELECT MAX(posted_at) FROM public.loan_ledger p
                                       WHERE p.loan_id = l.id AND p.entry_type = 'repayment') <= l.due_date)),
    'loans_repaid_late', (SELECT COUNT(*) FROM public.loans l
        WHERE l.user_id = _user_id AND l.status IN ('repaid','closed') AND l.due_date IS NOT NULL
          AND EXISTS (SELECT 1 FROM public.loan_ledger d WHERE d.loan_id = l.id AND d.entry_type = 'disbursal')
          AND (SELECT MAX(posted_at) FROM public.loan_ledger p
                WHERE p.loan_id = l.id AND p.entry_type = 'repayment') > l.due_date),
    'loans_overdue_now', (SELECT COUNT(*) FROM public.loan_balances b JOIN public.loans l ON l.id = b.loan_id
        WHERE l.user_id = _user_id AND b.outstanding_paise > 0
          AND (l.status = 'overdue' OR (l.status IN ('disbursed','active') AND l.due_date < now()))),
    'bnpl_active', (SELECT COUNT(*) FROM public.bnpl_orders WHERE user_id = _user_id AND status = 'active'),
    'kyc_verified', (SELECT CASE WHEN kyc_status = 'verified' THEN 1 ELSE 0 END FROM public.profiles WHERE user_id = _user_id),
    'account_age_days', (SELECT GREATEST(0, EXTRACT(DAY FROM now() - created_at)::int) FROM public.profiles WHERE user_id = _user_id)
  );

  -- Add up points for every feature in the active model.
  FOR r IN
    SELECT DISTINCT ON (s.feature) s.feature, s.points,
           (SELECT MAX(points) FROM public.scorecard_bins m WHERE m.model_version = v_model AND m.feature = s.feature) AS best
      FROM public.scorecard_bins s
     WHERE s.model_version = v_model
       AND (s.min_value IS NULL OR COALESCE((f ->> s.feature)::numeric, 0) >= s.min_value)
       AND (s.max_value IS NULL OR COALESCE((f ->> s.feature)::numeric, 0) <  s.max_value)
     ORDER BY s.feature, s.bin_no
  LOOP
    v_score := v_score + r.points;
    pts := pts || jsonb_build_object(r.feature, r.points);
    max_pts := max_pts || jsonb_build_object(r.feature, r.best);
  END LOOP;

  IF v_score = 0 THEN
    RAISE EXCEPTION 'credit model % has no bins', v_model;
  END IF;
  v_score := GREATEST(300, LEAST(900, v_score));
  v_band := CASE
{band_case}
    ELSE 'very_poor'
  END;

  INSERT INTO public.credit_score_history (user_id, score, band, factors, model_version)
  VALUES (_user_id, v_score, v_band, f || jsonb_build_object('points', pts, 'max_points', max_pts), v_model);

  PERFORM set_config('rozanapay.internal', 'on', true);
  UPDATE public.profiles SET credit_score = v_score, updated_at = now() WHERE user_id = _user_id;
  PERFORM set_config('rozanapay.internal', 'off', true);
  RETURN v_score;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.compute_credit_score(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.compute_credit_score(uuid) TO authenticated;
""")
