// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my RozanaPay profile",
  description: "Return the signed-in user's RozanaPay profile including name, phone, occupation, city, KYC status and current credit score.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { profile: data } };
  }
});

// src/lib/mcp/tools/get-summary.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_summary_default = defineTool2({
  name: "get_summary",
  title: "Get financial summary",
  description: "High-level snapshot for the signed-in user: 30-day income and expenses, savings balance, active loans and credit score.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb2(ctx);
    const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1e3).toISOString();
    const [incomeRes, expRes, savRes, loansRes, profRes] = await Promise.all([
      client.from("income_logs").select("amount").gte("date", since),
      client.from("expenses").select("amount").gte("date", since),
      client.from("savings_goals").select("current_amount, target_amount, title"),
      client.from("loans").select("id, amount, status, due_date").in("status", ["disbursed", "approved", "pending"]),
      client.from("profiles").select("credit_score, kyc_status").eq("user_id", ctx.getUserId()).maybeSingle()
    ]);
    const err = incomeRes.error || expRes.error || savRes.error || loansRes.error || profRes.error;
    if (err) return { content: [{ type: "text", text: err.message }], isError: true };
    const income30 = (incomeRes.data ?? []).reduce((s, r) => s + Number(r.amount ?? 0), 0);
    const expense30 = (expRes.data ?? []).reduce((s, r) => s + Number(r.amount ?? 0), 0);
    const savings = (savRes.data ?? []).reduce((s, r) => s + Number(r.current_amount ?? 0), 0);
    const activeLoans = loansRes.data ?? [];
    const summary = {
      income_30d_rupees: income30,
      expense_30d_rupees: expense30,
      net_30d_rupees: income30 - expense30,
      savings_total_rupees: savings,
      savings_goals: savRes.data,
      active_loans: activeLoans,
      credit_score: profRes.data?.credit_score ?? null,
      kyc_status: profRes.data?.kyc_status ?? null
    };
    return {
      content: [{
        type: "text",
        text: `Last 30 days: earned \u20B9${income30.toLocaleString("en-IN")}, spent \u20B9${expense30.toLocaleString("en-IN")} (net \u20B9${(income30 - expense30).toLocaleString("en-IN")}). Savings: \u20B9${savings.toLocaleString("en-IN")}. Active loans: ${activeLoans.length}. Credit score: ${profRes.data?.credit_score ?? "n/a"}.`
      }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-income.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_income_default = defineTool3({
  name: "list_income",
  title: "List recent income",
  description: "List the signed-in user's recent income entries. Defaults to the last 30 days.",
  inputSchema: {
    days: z.number().int().positive().max(365).optional().describe("How many trailing days to include. Default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const d = days ?? 30;
    const since = new Date(Date.now() - d * 24 * 60 * 60 * 1e3).toISOString();
    const { data, error } = await sb3(ctx).from("income_logs").select("id, amount, source, note, date, created_at").gte("date", since).order("date", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((s, r) => s + Number(r.amount ?? 0), 0);
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} entries totalling \u20B9${total.toLocaleString("en-IN")} in the last ${d} days.` }],
      structuredContent: { total_rupees: total, count: data?.length ?? 0, entries: data }
    };
  }
});

// src/lib/mcp/tools/log-income.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_income_default = defineTool4({
  name: "log_income",
  title: "Log income",
  description: "Record a new income entry (in rupees) for the signed-in user.",
  inputSchema: {
    amount: z2.number().positive().describe("Amount in rupees."),
    source: z2.string().trim().min(1).describe("Where the income came from, e.g. 'Uber', 'Tips', 'Delivery'."),
    note: z2.string().optional().describe("Optional note."),
    date: z2.string().datetime().optional().describe("ISO timestamp. Defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ amount, source, note, date }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("income_logs").insert({ user_id: ctx.getUserId(), amount, source, note: note ?? null, date: date ?? (/* @__PURE__ */ new Date()).toISOString() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged \u20B9${amount} from ${source}.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/log-expense.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_expense_default = defineTool5({
  name: "log_expense",
  title: "Log expense",
  description: "Record a new expense (in rupees) for the signed-in user.",
  inputSchema: {
    amount: z3.number().positive().describe("Amount in rupees."),
    category: z3.string().trim().min(1).describe("Expense category, e.g. 'Food', 'Fuel', 'Rent'."),
    note: z3.string().optional(),
    date: z3.string().datetime().optional().describe("ISO timestamp. Defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ amount, category, note, date }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb5(ctx).from("expenses").insert({ user_id: ctx.getUserId(), amount, category, note: note ?? null, date: date ?? (/* @__PURE__ */ new Date()).toISOString() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged \u20B9${amount} expense on ${category}.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/list-loans.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_loans_default = defineTool6({
  name: "list_loans",
  title: "List my loans",
  description: "List all loans (pending, active, repaid) for the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb6(ctx).from("loans").select("id, amount, status, interest_rate, duration, due_date, approved_at, created_at").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Found ${data?.length ?? 0} loans.` }], structuredContent: { loans: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pkgcgzrehvlzdsxbzaqp";
var mcp_default = defineMcp({
  name: "rozanapay-mcp",
  title: "RozanaPay",
  version: "0.1.0",
  instructions: "Financial tools for RozanaPay users (gig workers in India). Read the signed-in user's income, expenses, savings, loans and credit score, and log new income or expense entries. All amounts are in Indian rupees.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, get_summary_default, list_income_default, log_income_default, log_expense_default, list_loans_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
