-- ============================================================================
-- Credit scorecard scorecard-v1 (generated by ml/credit-model/export_sql.py — do not hand-edit)
-- Logistic-regression scorecard on WoE-binned behaviour features.
-- Trained on SYNTHETIC data: retrain on real repayment outcomes before real lending.
-- Holdout metrics and method: ml/credit-model/MODEL_CARD.md
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.scorecard_bins (
  model_version text NOT NULL,
  feature text NOT NULL,
  label text NOT NULL,
  bin_no int NOT NULL,
  min_value numeric,          -- inclusive; NULL = no lower bound
  max_value numeric,          -- exclusive; NULL = no upper bound
  points int NOT NULL,
  woe numeric NOT NULL,
  train_default_rate numeric NOT NULL,
  PRIMARY KEY (model_version, feature, bin_no)
);
ALTER TABLE public.scorecard_bins ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.scorecard_bins TO authenticated;
GRANT ALL ON public.scorecard_bins TO service_role;
DO $p$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'scorecard_bins'
                 AND policyname = 'Signed-in users can read the scorecard') THEN
    CREATE POLICY "Signed-in users can read the scorecard" ON public.scorecard_bins
      FOR SELECT TO authenticated USING (true);
  END IF;
END $p$;

INSERT INTO public.scorecard_bins
  (model_version, feature, label, bin_no, min_value, max_value, points, woe, train_default_rate)
VALUES
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 0, NULL, 8.0, 20, -1.0127, 0.2481),
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 1, 8.0, 11.0, 27, -0.8523, 0.2194),
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 2, 11.0, 13.0, 41, -0.5113, 0.1665),
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 3, 13.0, 15.0, 55, -0.2092, 0.1287),
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 4, 15.0, 16.0, 63, -0.0267, 0.1095),
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 5, 16.0, 18.0, 74, 0.239, 0.0862),
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 6, 18.0, 19.0, 91, 0.6246, 0.0602),
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 7, 19.0, 21.0, 102, 0.8746, 0.0475),
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 8, 21.0, 23.0, 122, 1.3422, 0.0303),
  ('scorecard-v1', 'income_days_30', 'Days with income (30d)', 9, 23.0, NULL, 138, 1.7136, 0.0211),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 0, NULL, 3300.0, 61, -0.7955, 0.2098),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 1, 3300.0, 4700.0, 62, -0.4748, 0.1615),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 2, 4700.0, 5900.0, 63, -0.2523, 0.1336),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 3, 5900.0, 7100.0, 64, -0.0329, 0.1102),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 4, 7100.0, 8400.0, 64, 0.0707, 0.1004),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 5, 8400.0, 9800.0, 64, 0.1953, 0.0897),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 6, 9800.0, 12000.0, 65, 0.2958, 0.0818),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 7, 12000.0, 14000.0, 65, 0.4306, 0.0722),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 8, 14000.0, 18000.0, 66, 0.6196, 0.0605),
  ('scorecard-v1', 'income_total_30', 'Income earned (30d)', 9, 18000.0, NULL, 67, 0.7764, 0.0522),
  ('scorecard-v1', 'active_weeks_12', 'Active weeks (12w)', 0, NULL, 2.0, 55, -0.5527, 0.1723),
  ('scorecard-v1', 'active_weeks_12', 'Active weeks (12w)', 1, 2.0, 3.0, 56, -0.4396, 0.1568),
  ('scorecard-v1', 'active_weeks_12', 'Active weeks (12w)', 2, 3.0, 5.0, 57, -0.411, 0.1531),
  ('scorecard-v1', 'active_weeks_12', 'Active weeks (12w)', 3, 5.0, 6.0, 59, -0.2618, 0.1347),
  ('scorecard-v1', 'active_weeks_12', 'Active weeks (12w)', 4, 6.0, 7.0, 63, -0.0182, 0.1087),
  ('scorecard-v1', 'active_weeks_12', 'Active weeks (12w)', 5, 7.0, 8.0, 67, 0.179, 0.091),
  ('scorecard-v1', 'active_weeks_12', 'Active weeks (12w)', 6, 8.0, 9.0, 73, 0.5685, 0.0635),
  ('scorecard-v1', 'active_weeks_12', 'Active weeks (12w)', 7, 9.0, 10.0, 79, 0.931, 0.045),
  ('scorecard-v1', 'active_weeks_12', 'Active weeks (12w)', 8, 10.0, NULL, 86, 1.3314, 0.0306),
  ('scorecard-v1', 'expense_ratio_30', 'Spending vs income (30d)', 0, NULL, 0.51, 118, 1.1698, 0.0358),
  ('scorecard-v1', 'expense_ratio_30', 'Spending vs income (30d)', 1, 0.51, 0.6, 102, 0.8185, 0.0501),
  ('scorecard-v1', 'expense_ratio_30', 'Spending vs income (30d)', 2, 0.6, 0.67, 91, 0.5856, 0.0625),
  ('scorecard-v1', 'expense_ratio_30', 'Spending vs income (30d)', 3, 0.67, 0.73, 87, 0.5017, 0.0676),
  ('scorecard-v1', 'expense_ratio_30', 'Spending vs income (30d)', 4, 0.73, 0.78, 84, 0.4272, 0.0724),
  ('scorecard-v1', 'expense_ratio_30', 'Spending vs income (30d)', 5, 0.78, 0.84, 74, 0.2292, 0.087),
  ('scorecard-v1', 'expense_ratio_30', 'Spending vs income (30d)', 6, 0.84, 0.9, 66, 0.0532, 0.102),
  ('scorecard-v1', 'expense_ratio_30', 'Spending vs income (30d)', 7, 0.9, 0.96, 58, -0.1129, 0.1183),
  ('scorecard-v1', 'expense_ratio_30', 'Spending vs income (30d)', 8, 0.96, NULL, 19, -0.9526, 0.2371),
  ('scorecard-v1', 'loans_repaid_on_time', 'Loans repaid on time', 0, NULL, 1.0, 63, -0.1011, 0.1171),
  ('scorecard-v1', 'loans_repaid_on_time', 'Loans repaid on time', 1, 1.0, 2.0, 64, 0.1055, 0.0974),
  ('scorecard-v1', 'loans_repaid_on_time', 'Loans repaid on time', 2, 2.0, NULL, 67, 0.4176, 0.0731),
  ('scorecard-v1', 'loans_repaid_late', 'Loans repaid late', 0, NULL, 1.0, 69, 0.1547, 0.0931),
  ('scorecard-v1', 'loans_repaid_late', 'Loans repaid late', 1, 1.0, NULL, 39, -0.7392, 0.2007),
  ('scorecard-v1', 'loans_overdue_now', 'Loans overdue now', 0, NULL, 1.0, 67, 0.0523, 0.1022),
  ('scorecard-v1', 'loans_overdue_now', 'Loans overdue now', 1, 1.0, NULL, 0, -1.0148, 0.2484),
  ('scorecard-v1', 'bnpl_active', 'Active BNPL orders', 0, NULL, 1.0, 73, 0.2285, 0.0871),
  ('scorecard-v1', 'bnpl_active', 'Active BNPL orders', 1, 1.0, 2.0, 52, -0.2735, 0.1361),
  ('scorecard-v1', 'bnpl_active', 'Active BNPL orders', 2, 2.0, NULL, 33, -0.7391, 0.2006),
  ('scorecard-v1', 'kyc_verified', 'KYC verified', 0, NULL, 1.0, 53, -0.303, 0.1397),
  ('scorecard-v1', 'kyc_verified', 'KYC verified', 1, 1.0, NULL, 80, 0.462, 0.0702)
ON CONFLICT (model_version, feature, bin_no) DO UPDATE
  SET label = EXCLUDED.label, min_value = EXCLUDED.min_value, max_value = EXCLUDED.max_value,
      points = EXCLUDED.points, woe = EXCLUDED.woe, train_default_rate = EXCLUDED.train_default_rate;

INSERT INTO public.app_settings (key, value) VALUES ('credit_model_version', 'scorecard-v1')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

CREATE OR REPLACE FUNCTION public.compute_credit_score(_user_id uuid)
RETURNS int LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_model text;
  f jsonb;              -- feature values
  pts jsonb := '{}'::jsonb;
  max_pts jsonb := '{}'::jsonb;
  r record;
  v_income bigint; v_expense bigint;
  v_score int := 0; v_band text;
BEGIN
  IF auth.uid() IS NOT NULL AND auth.uid() <> _user_id AND NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  SELECT value INTO v_model FROM public.app_settings WHERE key = 'credit_model_version';
  v_model := COALESCE(v_model, 'scorecard-v1');

  SELECT COALESCE(SUM(amount), 0) INTO v_income FROM public.income_logs
   WHERE user_id = _user_id AND date > now() - interval '30 days';
  SELECT COALESCE(SUM(amount), 0) INTO v_expense FROM public.expenses
   WHERE user_id = _user_id AND date > now() - interval '30 days';

  -- Features: names and definitions must match ml/credit-model/generate_data.py
  f := jsonb_build_object(
    'income_days_30', (SELECT COUNT(DISTINCT (date AT TIME ZONE 'Asia/Kolkata')::date) FROM public.income_logs
                        WHERE user_id = _user_id AND date > now() - interval '30 days'),
    'income_total_30', v_income,
    'active_weeks_12', (SELECT COUNT(DISTINCT date_trunc('week', date AT TIME ZONE 'Asia/Kolkata')) FROM public.income_logs
                        WHERE user_id = _user_id AND date > now() - interval '84 days'),
    'expense_ratio_30', CASE WHEN v_income > 0 THEN LEAST(round(v_expense::numeric / v_income, 3), 2.0) ELSE 2.0 END,
    'savings_balance', (SELECT COALESCE(SUM(current_amount), 0) FROM public.savings_goals WHERE user_id = _user_id),
    -- only loans that actually paid out count (no fake history)
    'loans_repaid_on_time', (SELECT COUNT(*) FROM public.loans l
        WHERE l.user_id = _user_id AND l.status IN ('repaid','closed')
          AND EXISTS (SELECT 1 FROM public.loan_ledger d WHERE d.loan_id = l.id AND d.entry_type = 'disbursal')
          AND (l.due_date IS NULL OR (SELECT MAX(posted_at) FROM public.loan_ledger p
                                       WHERE p.loan_id = l.id AND p.entry_type = 'repayment') <= l.due_date)),
    'loans_repaid_late', (SELECT COUNT(*) FROM public.loans l
        WHERE l.user_id = _user_id AND l.status IN ('repaid','closed') AND l.due_date IS NOT NULL
          AND EXISTS (SELECT 1 FROM public.loan_ledger d WHERE d.loan_id = l.id AND d.entry_type = 'disbursal')
          AND (SELECT MAX(posted_at) FROM public.loan_ledger p
                WHERE p.loan_id = l.id AND p.entry_type = 'repayment') > l.due_date),
    'loans_overdue_now', (SELECT COUNT(*) FROM public.loan_balances b JOIN public.loans l ON l.id = b.loan_id
        WHERE l.user_id = _user_id AND b.outstanding_paise > 0
          AND (l.status = 'overdue' OR (l.status IN ('disbursed','active') AND l.due_date < now()))),
    'bnpl_active', (SELECT COUNT(*) FROM public.bnpl_orders WHERE user_id = _user_id AND status = 'active'),
    'kyc_verified', (SELECT CASE WHEN kyc_status = 'verified' THEN 1 ELSE 0 END FROM public.profiles WHERE user_id = _user_id),
    'account_age_days', (SELECT GREATEST(0, EXTRACT(DAY FROM now() - created_at)::int) FROM public.profiles WHERE user_id = _user_id)
  );

  -- Add up points for every feature in the active model.
  FOR r IN
    SELECT DISTINCT ON (s.feature) s.feature, s.points,
           (SELECT MAX(points) FROM public.scorecard_bins m WHERE m.model_version = v_model AND m.feature = s.feature) AS best
      FROM public.scorecard_bins s
     WHERE s.model_version = v_model
       AND (s.min_value IS NULL OR COALESCE((f ->> s.feature)::numeric, 0) >= s.min_value)
       AND (s.max_value IS NULL OR COALESCE((f ->> s.feature)::numeric, 0) <  s.max_value)
     ORDER BY s.feature, s.bin_no
  LOOP
    v_score := v_score + r.points;
    pts := pts || jsonb_build_object(r.feature, r.points);
    max_pts := max_pts || jsonb_build_object(r.feature, r.best);
  END LOOP;

  IF v_score = 0 THEN
    RAISE EXCEPTION 'credit model % has no bins', v_model;
  END IF;
  v_score := GREATEST(300, LEAST(900, v_score));
  v_band := CASE
    WHEN v_score >= 800 THEN 'excellent'
    WHEN v_score >= 700 THEN 'good'
    WHEN v_score >= 600 THEN 'fair'
    WHEN v_score >= 500 THEN 'poor'
    ELSE 'very_poor'
  END;

  INSERT INTO public.credit_score_history (user_id, score, band, factors, model_version)
  VALUES (_user_id, v_score, v_band, f || jsonb_build_object('points', pts, 'max_points', max_pts), v_model);

  PERFORM set_config('rozanapay.internal', 'on', true);
  UPDATE public.profiles SET credit_score = v_score, updated_at = now() WHERE user_id = _user_id;
  PERFORM set_config('rozanapay.internal', 'off', true);
  RETURN v_score;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.compute_credit_score(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.compute_credit_score(uuid) TO authenticated;

